// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/claude/v1/messages": {
            "post": {
                "description": "Sends a message to the Claude model. Supports both standard JSON response and streaming (SSE) response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "Claude"
                ],
                "summary": "Send Message (Claude)",
                "parameters": [
                    {
                        "description": "Message Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream of dto.StreamEvent JSON objects",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/claude/v1/messages/count_tokens": {
            "post": {
                "description": "Estimates the number of tokens for a request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claude"
                ],
                "summary": "Count Tokens (Claude)",
                "parameters": [
                    {
                        "description": "Message Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/claude/v1/models": {
            "get": {
                "description": "Returns a list of available Claude models",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claude"
                ],
                "summary": "List Claude Models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/claude/v1/models/{model_id}": {
            "get": {
                "description": "Get details of a specific Claude model",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claude"
                ],
                "summary": "Get Claude Model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/gemini/v1beta/deepresearch": {
            "post": {
                "description": "Performs deep research on a topic using Gemini.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gemini"
                ],
                "summary": "Deep Research (synchronous)",
                "parameters": [
                    {
                        "description": "Deep Research Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeepResearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeepResearchResponse"
                        }
                    }
                }
            }
        },
        "/gemini/v1beta/models": {
            "get": {
                "description": "Returns a list of models supported by the Gemini API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gemini"
                ],
                "summary": "List Gemini Models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GeminiModelsResponse"
                        }
                    }
                }
            }
        },
        "/gemini/v1beta/models/{model}:generateContent": {
            "post": {
                "description": "Generates content using the Gemini model",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gemini"
                ],
                "summary": "Generate Content (Gemini)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Generate Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GeminiGenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GeminiGenerateResponse"
                        }
                    }
                }
            }
        },
        "/gemini/v1beta/models/{model}:streamGenerateContent": {
            "post": {
                "description": "Streams generated content using the Gemini model",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gemini"
                ],
                "summary": "Stream Generate Content (Gemini)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Generate Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GeminiGenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Chunked JSON response",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the service. Used by Docker/K8s/cloud platforms to monitor the service.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "service": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/openai/v1/chat/completions": {
            "post": {
                "description": "Generates a completion for the chat message. Supports both standard JSON and streaming (SSE) response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "OpenAI"
                ],
                "summary": "Chat Completions (OpenAI)",
                "parameters": [
                    {
                        "description": "Chat Completion Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChatCompletionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream of dto.ChatCompletionChunk JSON objects",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/openai/v1/models": {
            "get": {
                "description": "Returns a list of models supported by the OpenAI-compatible API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OpenAI"
                ],
                "summary": "List OpenAI Models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ModelListResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Candidate": {
            "type": "object",
            "properties": {
                "content": {
                    "$ref": "#/definitions/dto.Content"
                },
                "finishMessage": {
                    "type": "string"
                },
                "finishReason": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                }
            }
        },
        "dto.ChatCompletionMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "dto.ChatCompletionRequest": {
            "type": "object"
        },
        "dto.ChatCompletionResponse": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Choice"
                    }
                },
                "created": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/models.Usage"
                }
            }
        },
        "dto.ChatCompletionResponseMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "tool_calls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ChatCompletionToolCall"
                    }
                }
            }
        },
        "dto.ChatCompletionToolCall": {
            "type": "object",
            "properties": {
                "function": {
                    "$ref": "#/definitions/dto.ChatCompletionToolCallFunction"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.ChatCompletionToolCallFunction": {
            "type": "object",
            "properties": {
                "arguments": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.Choice": {
            "type": "object",
            "properties": {
                "finish_reason": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "message": {
                    "$ref": "#/definitions/dto.ChatCompletionResponseMessage"
                }
            }
        },
        "dto.ConfigContent": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "for tool_use",
                    "type": "string"
                },
                "input": {
                    "description": "for tool_use",
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "description": "for tool_use",
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "type": {
                    "description": "\"text\" or \"tool_use\"",
                    "type": "string"
                }
            }
        },
        "dto.Content": {
            "type": "object"
        },
        "dto.DeepResearchRequest": {
            "type": "object",
            "properties": {
                "language": {
                    "description": "Language for the response (optional, e.g. \"en\", \"vi\")",
                    "type": "string"
                },
                "max_sources": {
                    "description": "MaxSources maximum number of web sources to consult (optional)",
                    "type": "integer"
                },
                "model": {
                    "description": "Model to use (optional, defaults to best available)",
                    "type": "string"
                },
                "query": {
                    "description": "Query is the research topic or question",
                    "type": "string"
                }
            }
        },
        "dto.DeepResearchResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "description": "CompletedAt timestamp (Unix seconds), 0 if not completed",
                    "type": "integer"
                },
                "created_at": {
                    "description": "CreatedAt timestamp (Unix seconds)",
                    "type": "integer"
                },
                "duration_ms": {
                    "description": "DurationMs total research duration in milliseconds",
                    "type": "integer"
                },
                "error": {
                    "description": "Error message if status is \"failed\"",
                    "type": "string"
                },
                "id": {
                    "description": "ID of this research session",
                    "type": "string"
                },
                "model": {
                    "description": "Model used",
                    "type": "string"
                },
                "query": {
                    "description": "Query that was researched",
                    "type": "string"
                },
                "sources": {
                    "description": "Sources used in research",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ResearchSource"
                    }
                },
                "status": {
                    "description": "Status: \"in_progress\", \"completed\", \"failed\"",
                    "type": "string"
                },
                "steps": {
                    "description": "Steps of research performed",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ResearchStep"
                    }
                },
                "summary": {
                    "description": "Summary is the synthesized research report",
                    "type": "string"
                }
            }
        },
        "dto.GeminiGenerateRequest": {
            "type": "object"
        },
        "dto.GeminiGenerateResponse": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Candidate"
                    }
                },
                "usageMetadata": {
                    "$ref": "#/definitions/dto.UsageMetadata"
                }
            }
        },
        "dto.GeminiModel": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "supportedGenerationMethods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dto.GeminiModelsResponse": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GeminiModel"
                    }
                }
            }
        },
        "dto.InlineData": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                }
            }
        },
        "dto.MessageRequest": {
            "type": "object"
        },
        "dto.MessageResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ConfigContent"
                    }
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "role": {
                    "description": "\"assistant\"",
                    "type": "string"
                },
                "stop_reason": {
                    "type": "string"
                },
                "type": {
                    "description": "\"message\"",
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/models.Usage"
                }
            }
        },
        "dto.ResearchSource": {
            "type": "object",
            "properties": {
                "domain": {
                    "description": "Domain of the source",
                    "type": "string"
                },
                "snippet": {
                    "description": "Snippet relevant excerpt from the source",
                    "type": "string"
                },
                "title": {
                    "description": "Title of the source page",
                    "type": "string"
                },
                "url": {
                    "description": "URL of the source",
                    "type": "string"
                }
            }
        },
        "dto.ResearchStep": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description of what this step did",
                    "type": "string"
                },
                "query": {
                    "description": "Query used in this step (for search steps)",
                    "type": "string"
                },
                "result": {
                    "description": "Result summary of this step",
                    "type": "string"
                },
                "step_number": {
                    "description": "StepNumber ordinal step number",
                    "type": "integer"
                },
                "type": {
                    "description": "Type of step: \"search\", \"read\", \"synthesize\", \"outline\", \"write\"",
                    "type": "string"
                }
            }
        },
        "dto.UsageMetadata": {
            "type": "object",
            "properties": {
                "candidatesTokenCount": {
                    "type": "integer"
                },
                "promptTokenCount": {
                    "type": "integer"
                },
                "totalTokenCount": {
                    "type": "integer"
                }
            }
        },
        "models.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "models.ModelData": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "integer"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "owned_by": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.ModelListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ModelData"
                    }
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "models.Usage": {
            "type": "object",
            "properties": {
                "completion_tokens": {
                    "type": "integer"
                },
                "input_tokens": {
                    "type": "integer"
                },
                "output_tokens": {
                    "type": "integer"
                },
                "prompt_tokens": {
                    "type": "integer"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4981",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Gemini Web To API",
	Description:      "✨Reverse-engineered API for Gemini web app. It can be used as a genuine API key from OpenAI, Gemini, and Claude.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
