// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/chat/completions": {
            "post": {
                "description": "Accepts requests in OpenAI format",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OpenAI Compatible"
                ],
                "summary": "OpenAI-compatible chat completions",
                "parameters": [
                    {
                        "description": "Chat request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/openai.ChatCompletionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openai.ChatCompletionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/openai.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/openai.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/embeddings": {
            "post": {
                "description": "Converts input text to vector embeddings (Placeholder)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OpenAI Compatible"
                ],
                "summary": "Create embeddings",
                "parameters": [
                    {
                        "description": "Embeddings request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/openai.EmbeddingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openai.EmbeddingsResponse"
                        }
                    }
                }
            }
        },
        "/v1/models": {
            "get": {
                "description": "Returns a list of models supported by this server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OpenAI Compatible"
                ],
                "summary": "List models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openai.ModelListResponse"
                        }
                    }
                }
            }
        },
        "/v1beta/models": {
            "get": {
                "description": "Returns models supported by the Gemini provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gemini v1beta"
                ],
                "summary": "List Gemini Models (v1beta)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gemini.GeminiModelsResponse"
                        }
                    }
                }
            }
        },
        "/v1beta/models/{model}:embedContent": {
            "post": {
                "description": "Returns vector embeddings for the provided content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gemini v1beta"
                ],
                "summary": "Embed Content (v1beta)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model name",
                        "name": "model",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Embed request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gemini.GeminiEmbedRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gemini.GeminiEmbedResponse"
                        }
                    }
                }
            }
        },
        "/v1beta/models/{model}:generateContent": {
            "post": {
                "description": "Compatible with official Google Gemini API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gemini v1beta"
                ],
                "summary": "Generate Content (v1beta)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model name",
                        "name": "model",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Gemini request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gemini.GeminiGenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gemini.GeminiGenerateResponse"
                        }
                    }
                }
            }
        },
        "/v1beta/models/{model}:streamGenerateContent": {
            "post": {
                "description": "Returns a stream of JSON chunks (standard Gemini format)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gemini v1beta"
                ],
                "summary": "Stream Generate Content (v1beta)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model name",
                        "name": "model",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Gemini request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gemini.GeminiGenerateRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "gemini.Candidate": {
            "type": "object",
            "properties": {
                "content": {
                    "$ref": "#/definitions/gemini.Content"
                },
                "finishReason": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                }
            }
        },
        "gemini.Content": {
            "type": "object",
            "properties": {
                "parts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gemini.Part"
                    }
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "gemini.EmbeddingValues": {
            "type": "object",
            "properties": {
                "values": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "gemini.GeminiEmbedRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "$ref": "#/definitions/gemini.Content"
                }
            }
        },
        "gemini.GeminiEmbedResponse": {
            "type": "object",
            "properties": {
                "embedding": {
                    "$ref": "#/definitions/gemini.EmbeddingValues"
                }
            }
        },
        "gemini.GeminiGenerateRequest": {
            "type": "object",
            "properties": {
                "contents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gemini.Content"
                    }
                },
                "generationConfig": {
                    "$ref": "#/definitions/gemini.GenerationConfig"
                }
            }
        },
        "gemini.GeminiGenerateResponse": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gemini.Candidate"
                    }
                },
                "usageMetadata": {
                    "$ref": "#/definitions/gemini.UsageMetadata"
                }
            }
        },
        "gemini.GeminiModel": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "inputTokenLimit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "outputTokenLimit": {
                    "type": "integer"
                },
                "supportedGenerationMethods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "gemini.GeminiModelsResponse": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gemini.GeminiModel"
                    }
                }
            }
        },
        "gemini.GenerationConfig": {
            "type": "object",
            "properties": {
                "maxOutputTokens": {
                    "type": "integer"
                },
                "stopSequences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "temperature": {
                    "type": "number"
                },
                "topK": {
                    "type": "integer"
                },
                "topP": {
                    "type": "number"
                }
            }
        },
        "gemini.InlineData": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Base64",
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                }
            }
        },
        "gemini.Part": {
            "type": "object",
            "properties": {
                "inlineData": {
                    "$ref": "#/definitions/gemini.InlineData"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "gemini.UsageMetadata": {
            "type": "object",
            "properties": {
                "candidatesTokenCount": {
                    "type": "integer"
                },
                "promptTokenCount": {
                    "type": "integer"
                },
                "totalTokenCount": {
                    "type": "integer"
                }
            }
        },
        "openai.ChatCompletionRequest": {
            "type": "object",
            "properties": {
                "max_tokens": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/openai.Message"
                    }
                },
                "model": {
                    "type": "string"
                },
                "stream": {
                    "type": "boolean"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "openai.ChatCompletionResponse": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/openai.Choice"
                    }
                },
                "created": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/openai.Usage"
                }
            }
        },
        "openai.Choice": {
            "type": "object",
            "properties": {
                "finish_reason": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "message": {
                    "$ref": "#/definitions/openai.Message"
                }
            }
        },
        "openai.Embedding": {
            "type": "object",
            "properties": {
                "embedding": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "index": {
                    "type": "integer"
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "openai.EmbeddingsRequest": {
            "type": "object",
            "properties": {
                "input": {},
                "model": {
                    "type": "string"
                }
            }
        },
        "openai.EmbeddingsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/openai.Embedding"
                    }
                },
                "model": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/openai.Usage"
                }
            }
        },
        "openai.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "openai.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/openai.Error"
                }
            }
        },
        "openai.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "openai.ModelData": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "owned_by": {
                    "type": "string"
                }
            }
        },
        "openai.ModelListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/openai.ModelData"
                    }
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "openai.Usage": {
            "type": "object",
            "properties": {
                "completion_tokens": {
                    "type": "integer"
                },
                "prompt_tokens": {
                    "type": "integer"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AI Bridges API",
	Description:      "WebAI-to-API service for Go - Convert web-based AI services to REST APIs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
